# Dependencies
markdown:         kramdown
highlighter:      rouge
include:          ['_pages']

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Intro to Greco-Roman Gender and Sexuality
tagline:          'Intro to Greco-Roman Gender and Sexuality'
course_number:    'CLAS 199 01'
semester:         'Spring 2020'
location:         'College of the Holy Cross'
url:              https://dlibatique.github.io/CLAS199-S20
baseurl:          /

author:
  name:           'Daniel Libatique'
  url:            https://dlibatique.github.io

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dlibatique/CLAS199-S20
